version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - '54323:5432'
    volumes:
      - pgdata18:/var/lib/postgresql/data

volumes:
  pgdata18:
